language: python
python:
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
install:
  - env
  - pip install . --use-mirrors --environment=$HOME/virtualenv
  - pip install unittest2 --use-mirrors --environment=$HOME/virtualenv
script:
  - bin/unit2 discover icalendar []
