language: python
python:
  - "2.4"
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
install:
  - pip help install
  - pip install --upgrade pip
  - pip install --use-mirrors -E=$HOME/virtualenv/python$TRAVIS_PYTHON_VERSION .
  - pip install --use-mirrors --environment=$HOME/virtualenv/python$TRAVIS_PYTHON_VERSION unittest2
script:
  - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/bin/unit2 discover icalendar []
